#http://showrss.info personal url
feedURL: http://showrss.info/user/55838.rss?magnets=true&namespaces=true&name=null&quality=fhd&re=null
#transmission configuration
transmission: 
    host: 192.168.1.57:9091
    user: transmission
    password: transmission
    removeCompletes: yes

sourceFolder: /Volumes/U01/transmission/completes
targetFolder: /Volumes/U01/media/tvshows
videoExts: [".mp4", ".mkv", ".avi", ".wmv", ".mpg", ".mpeg"]
seriesFormat : "{name}/Season {season}/{name} - S{season}E{episode} - {title}"
testMode: yes

